isilon_host: 10.246.157.227
isilon_node_pool_name: h400_30tb_3.2tb-ssd_64gb
isilon_user: root
_isilon_password: "your_password"
result_filename: data/p3_test_driver/results/%(test)s_%(model)s_np%(np)d_%(timestamp)s_%(test_uuid)s.json.bz2
status_html: data/p3_test_driver/status/p3_test_driver.html
test_driver_log_filename: data/p3_test_driver/logs/p3_test_driver.log
