status_html: data/p3_test_driver/status/p3_test_driver.html
result_filename: data/p3_test_driver/results/%(test)s_%(test_uuid)s.json
test_driver_log_filename: data/p3_test_driver/logs/p3_test_driver.log
