batch_size: 256
batch_group_size: 10
data_dir_template: /mnt/isilon%d/data/imagenet-scratch/tfrecords1729-tiny
data_dir_template_count: 1
datasets_num_private_threads: 12
datasets_prefetch_buffer_size: 20
flush: false
fp16: true
host:
  - dgx2-1
#  - dgx2-2
#  - dgx2-3
isilon_host: 172.28.10.151
model: inception4
noop: false
np: 16
npernode: 16
num_batches: 250
num_intra_threads: 1
num_inter_threads: 2
repeat: 1
