batch_size: 256
batch_group_size: 10
data_dir_template: /mnt/isilon%d/data/imagenet-scratch/tfrecords-png
data_dir_template_count: 16
datasets_prefetch_buffer_size: 20
datasets_num_private_threads: 11
flush: false
fp16: true
fuse_decode_and_crop: false
model: trivial
noop: false
np: 16
npernode: 16
num_batches: 250
num_hosts: 1
num_inter_threads: 40
num_intra_threads: 1
repeat: 1
