batch_size: 256
#flush: true
host:
  - dl-worker1
  - dl-worker2
  - dl-worker3
  - dl-worker4
  - dl-worker5
  - dl-worker6
  - dl-worker7
  - dl-worker8
  - dl-worker11
  - dl-worker12
  - dl-worker13
  - dl-worker14
#  - dl-worker2.us-east4-a.c.isilon-hdfs-project.internal
#  - dl-worker9.us-east4-b.c.isilon-hdfs-project.internal
#  - dl-worker10.us-east4-b.c.isilon-hdfs-project.internal
input_file_specs:
  - "/mnt/filestore1/data/imagenet-scratch/tfrecords-7x/train-*"
#  - "/mnt/isilon1/data/imagenet-scratch/tfrecords-7x/train-*"
#  - "/mnt/isilon2/data/imagenet-scratch/tfrecords-7x/train-*"
#  - "/mnt/isilon3/data/imagenet-scratch/tfrecords-7x/train-*"
#  - "/mnt/isilon4/data/imagenet-scratch/tfrecords-7x/train-*"
install: true
#isilon_host: 172.28.10.151
metrics_directory: /imagenet-scratch/logs
np: 48
npernode: 80
num_threads: 0
parallel_interleave_cycle_length: 0
round_robin_files: true
run_sec: 300
sync: true
throttle_total_rate_bytes_per_sec: 0
warmup_sec: 120
