{
 "title": "Host Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "NVIDIA GPU usage per host",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(nvidia_gpu_duty_cycle) by (instance)"
    }
   ]
  },
  {
   "title": "Network RX per host",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device!~\"veth.*|lo\"}[5m])",
     "legendFormat": "{{group}} {{instance}} {{device}}"
    }
   ]
  },
  {
   "title": "CPU usage per host",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (avg by (group,instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])))",
     "legendFormat": "{{ group }} {{ instance }}"
    }
   ]
  },
  {
   "title": "Network TX per host",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{device!~\"veth.*|lo\"}[5m])",
     "legendFormat": "{{group}} {{instance}} {{device}}"
    }
   ]
  },
  {
   "title": "Disk write throughput per host",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_written_bytes_total[5m])) by (group,instance)",
     "legendFormat": "{{group}} {{instance}}"
    }
   ]
  },
  {
   "title": "Disk read throughput per host",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total[5m])) by (group,instance)",
     "legendFormat": "{{group}} {{instance}}"
    }
   ]
  }
 ]
}