{
 "title": "Host Metrics for Publishing",
 "time": { "from": "2019-10-18T18:02:00.000Z", "to": "2019-10-18T18:10:00.000Z" },
 "panels": [
  {
   "title": "Storage Network RX per host",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device!~\"veth.*|lo\",device=~\"bond0\"}[5m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Inter-switch Links - Switch Port RX",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{ifAlias=~\"isl-.*\"}[5m])",
     "legendFormat": "{{ ifAlias }}"
    }
   ]
  },
  {
   "title": "NVIDIA GPU usage per host",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(nvidia_gpu_duty_cycle) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "RoCE - Switch Port RX (15 sec average)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{ifAlias=~\"dgx2-.-c.\"}[5m])",
     "legendFormat": "{{ ifAlias }}"
    }
   ]
  },
  {
   "title": "CPU usage per host",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1.00 - (avg by (group,instance) (irate(node_cpu_seconds_total{mode=\"idle\",group=\"dgx\"}[5m])))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Isilon - Switch Port RX",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{ifAlias=~\"isilon-.*\"}[5m])",
     "legendFormat": "{{ ifAlias }}"
    }
   ]
  }
 ]
}