{
 "title": "RAPIDS Dashboard - Totals",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Storage Network RX (total)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{device!~\"veth.*|lo\",device=~\"enp134s0.*|enp12s0.*\"}[5m]))"
    }
   ]
  },
  {
   "title": "Local disk read throughput (total)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total{device=\"md1\"}[5m]))"
    }
   ]
  },
  {
   "title": "GPU usage (2 min avg)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(avg_over_time(nvidia_gpu_duty_cycle[2m]))"
    }
   ]
  },
  {
   "title": "Avg Memory Used per GPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(nvidia_gpu_memory_used_bytes)"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1.00 - (avg(irate(node_cpu_seconds_total{mode=\"idle\",group=~\"dgx\"}[5m])))"
    }
   ]
  }
 ]
}