{
 "title": "RAPIDS Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "GPU Duty Cycle",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "nvidia_gpu_duty_cycle",
     "legendFormat": "{{ instance }} {{ minor_number }}"
    }
   ]
  },
  {
   "title": "CPU usage per host",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1.00 - (avg by (group,instance) (irate(node_cpu_seconds_total{mode=\"idle\",group=~\"dgx|mgmt\"}[5m])))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Network RX per host",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device=~\"lo|enp53s0\"}[5m])",
     "legendFormat": "{{ instance }} {{ device }}"
    }
   ]
  },
  {
   "title": "GPU Memory Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nvidia_gpu_memory_used_bytes",
     "legendFormat": "{{ instance }} {{ minor_number }}"
    }
   ]
  }
 ]
}