version: '2'

services:
  prometheus:
    image: prom/prometheus:v2.11.1
    ports:
      - "9094:9090"
    volumes:
      - "${PROMETHEUS_DATA_DIR}:/prometheus"

  grafana:
    image: grafana/grafana:6.3.5
    ports:
      - "3000:3000"
    links:
      - prometheus
