- name: Slurm Management Nodes
  hosts: nvidia-mgmt
  roles:
    - ansible-slurm
  vars_files:
    - slurm_vars.yaml
  vars:
    slurm_roles: ["controller", "dbd", "exec"]

- name: Slurm Exec Nodes
  hosts: dgx2
  roles:
    - ansible-slurm
  vars_files:
    - slurm_vars.yaml
  vars:
    slurm_roles: ["exec"]
