
- name: Slurm all in One
  hosts: all
  roles:
    - ansible-slurm
  vars:
    slurm_cgroup_config:
      CgroupMountpoint: "/sys/fs/cgroup"
      CgroupAutomount: yes
      CgroupReleaseAgentDir: "/etc/slurm/cgroup"
      ConstrainCores: yes
      TaskAffinity: no
      ConstrainRAMSpace: yes
      ConstrainSwapSpace: no
      ConstrainDevices: no
      AllowedRamSpace: 100
      AllowedSwapSpace: 0
      MaxRAMPercent: 100
      MaxSwapPercent: 100
      MinRAMSpace: 30
    slurmdbd_config:
      DbdHost: localhost
      StorageType: "accounting_storage/none"
    slurm_config:
      AccountingStorageType: "accounting_storage/none"
      ClusterName: cluster
      FastSchedule: 1
      GresTypes: gpu
      JobAcctGatherType: "jobacct_gather/none"
      MpiDefault: none
      ProctrackType: "proctrack/cgroup"
      ReturnToService: 1
      SchedulerType: "sched/backfill"
      SelectType: "select/cons_res"
      SelectTypeParameters: "CR_Core"
#      SlurmctldHost: "slurmctl"
#      SlurmctldLogFile: "/var/log/slurm/slurmctld.log"
#      SlurmctldPidFile: "/var/run/slurmctld.pid"
#      SlurmdLogFile: "/var/log/slurm/slurmd.log"
#      SlurmdPidFile: "/var/run/slurmd.pid"
#      SlurmdSpoolDir: "/var/spool/slurmd"
#      StateSaveLocation: "/var/spool/slurmctld"
      SwitchType: "switch/none"
      TaskPlugin: "task/affinity,task/cgroup"
      TaskPluginParam: Sched
    slurm_create_dirs: yes
    slurm_create_user: yes
    slurm_gres_config:
      - File: /dev/nvidia[0-3]
        Name: gpu
        NodeName: gpu[01-10]
        Type: tesla
#    slurm_munge_key: "../../../munge.key"
    slurm_nodes:
      - name: "gpu[01-10]"
        CoresPerSocket: 18
        Gres: "gpu:tesla:4"
        Sockets: 2
        ThreadsPerCore: 2
      - name: "hop-claudio-ubuntu18-desktop"
        CoresPerSocket: 8
#        Gres: "gpu:tesla:4"
        Sockets: 1
        ThreadsPerCore: 1
    slurm_partitions:
      - name: gpu
#        Default: YES
        MaxTime: UNLIMITED
        Nodes: "gpu[01-10]"
      - name: debug
        Default: YES
        MaxTime: UNLIMITED
        Nodes: "hop-claudio-ubuntu18-desktop"
    slurm_roles: ['controller', 'exec', 'dbd']
#    slurm_roles: ['exec']
    slurm_user:
      comment: "Slurm Workload Manager"
      gid: 888
      group: slurm
      home: "/var/lib/slurm"
      name: slurm
      shell: "/usr/sbin/nologin"
      uid: 888
